---
# Create the root user before enabling security
# The new mongod.conf should be on the server, which enables security
- hosts: primary
  become_user: ubuntu
  become: yes

  tasks:
  - name: Create 'admin' database user with name 'dba' and password 'ABCABCABC'.
    community.mongodb.mongodb_user:
      database: admin
      name: dba
      password: ABCABCABC
      state: present
      roles: root
...
