---
# Installs Percona MongoDB
- hosts: dbservers
  become_user: ubuntu
  become: yes
  tasks:
    - name: Get latest percona release tool.
      shell: wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
    - name: Get latest Percona release information
      shell: dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
    - name: Enable Mongodb 5.0 in the Percona Release tool
      shell: sudo percona-release enable psmdb-50 release
    - name: Update all repos
      shell: sudo apt update
    - name: Get Mongosh Packages
      shell: wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add 
    - name: Install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - percona-server-mongodb
    - name: Start Percona MongoDB after install
      shell: systemctl start mongod
...
