---
# Create the root user before enabling security
# The new mongod.conf should be on the server, which enables security
- hosts: triserver
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Restart Mongo DB
    shell: |
      systemctl restart mongod
...
