---
# Restarts MongoDB instances
- hosts: dbservers
  become_user: ubuntu
  become: yes

  tasks:
    - name: Stop MongoDB
      shell: sudo systemctl stop mongod.service
    - name: Restart mongodb with mongod.conf
      shell: sudo systemctl start mongod.service
...
