---
# The following script installs some required software
# This includes the latest verson of Python and 
# the PIP package Pymongo. This is for Ubuntu.
- hosts: triserver
  become_user: root
  become: yes
  
  tasks:
  - name: Install packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
       - python3-pip
       - nano
       - vim
       - net-tools
       - wget
       - bash-completion
       - screen
       - unzip
       - mailutils
       - glances
       - tofrodos
       - tmux
       #- yum-utils

  - name: Install Pymongo
    pip: name=pymongo state=latest
...
